import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Nicholas McCracken
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // Initialize XML subtree variables necessary to print info to html page
        XMLTree title = channel.child(getChildElement(channel, "title"));
        XMLTree link = channel.child(getChildElement(channel, "link"));
        XMLTree desc = channel.child(getChildElement(channel, "description"));

        // Open and close all header tags which display at the top of html page
        out.println("<html>");
        out.println("<head>");
        out.print("<title>");

        // Print text child of title tag if it exists
        if (title.numberOfChildren() > 0) {
            out.print(title.child(0).label());
        } else {
            out.print("Empty Title");
        }
        out.println("</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>");

        // Print text child of title tag if it exists with hyperlink to channel
        if (title.numberOfChildren() > 0) {
            out.print("<a href=\"");
            out.print(link.child(0).label());
            out.print("\">");
            out.print(title.child(0).label());
            out.println("</a>");
        } else {
            out.print("Empty Title");
        }
        out.println("</h1>");
        out.print("<p>");

        // Print text child of description tag if it exists
        if (desc.numberOfChildren() > 0) {
            out.print(desc.child(0).label());
        } else {
            out.print("Empty Description");
        }
        out.println("</p>");

        // Print table with headers
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        // Close all tags left open by outputHeader function
        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        // Initialize return value to -1 to meet ensures clause
        int childIndex = -1;

        /*
         * Check every child of the XML tree for an instance of the tag, and
         * update return value if an instance is found
         */
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).label().equals(tag)) {
                childIndex = i;
            }
        }
        return childIndex;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // Create tag for a row and tag for a column within the row
        out.println("<tr>");
        out.print("<td>");

        // Print text child of publication date tag if it exists
        if (getChildElement(item, "pubDate") != -1
                && item.child(getChildElement(item, "pubDate"))
                        .numberOfChildren() > 0) {
            out.println(item.child(getChildElement(item, "pubDate")).child(0)
                    .label());
        } else {
            out.println("No date available");
        }
        // Close first column and create second column
        out.println("</td>");
        out.print("<td>");

        // Print text child of source tag if it exists
        if (getChildElement(item, "source") != -1
                && item.child(getChildElement(item, "source"))
                        .numberOfChildren() > 0) {
            // Initialize XML subtree variable for source tag for reusability
            XMLTree source = item.child(getChildElement(item, "source"));

            /*
             * Add hyperlink to text child of source tag if it has a url
             * attribute
             */
            if (source.hasAttribute("url")) {
                out.print("<a href=\"");
                out.print(source.attributeValue("url"));
                out.print("\">");
                out.print(source.child(0).label());
                out.println("</a>");
            } else {
                out.println(source.child(0).label());
            }
        } else {
            out.print("No source available");
        }
        // Close second column and create third column
        out.println("</td>");
        out.print("<td>");

        // Print text child of title tag if it exists
        if (getChildElement(item, "title") != -1 && item
                .child(getChildElement(item, "title")).numberOfChildren() > 0) {

            // Initialize XML subtree variable for title tag for reusability
            XMLTree title = item.child(getChildElement(item, "title"));

            /*
             * Add hyperlink to text child of title tag if text child of link
             * exists
             */
            if (getChildElement(item, "link") != -1) {
                out.print("<a href=\"");
                out.print(item.child(getChildElement(item, "link")).child(0));
                out.print("\">");
                out.print(title.child(0).label());
                out.println("</a>");
            } else {
                out.print(title.child(0).label());
            }
        } else {
            /*
             * Print text child of description if it exists and text child of
             * title does not
             */
            if (getChildElement(item, "description") != 1
                    && item.child(getChildElement(item, "description"))
                            .numberOfChildren() > 0) {
                out.println(item.child(getChildElement(item, "description"))
                        .child(0).label());
            } else {
                out.println("No title available");
            }
        }
        // Close third column and row
        out.println("</td>");
        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        // Open I/O streams
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        // Prompt user for RSS URL to create XMLTree object
        out.print("Enter the URL of an RSS 2.0 feed: ");
        String url = in.nextLine();
        XMLTree xml = new XMLTree1(url);

        // Prompt user for file with html extension to create file output stream
        out.print("Enter a name of an output file with an .html extension: ");
        String htmlFile = in.nextLine();
        SimpleWriter fileOut = new SimpleWriter1L(htmlFile);

        /*
         * Convert RSS feed to html output file as long as the url given has an
         * RSS root tag and is of RSS version 2.0
         */
        if (xml.label().equals("rss")
                && xml.attributeValue("version").equals("2.0")) {
            /*
             * Create a subtree for the root tag's channel child and print
             * opening tags to html output file
             */
            XMLTree channel = xml.child(0);
            outputHeader(channel, fileOut);

            /*
             * Print out a row in a table with the publication date, source, and
             * title (or description) for each instance of the item tag within
             * the channel subtree's children
             */
            for (int i = 0; i < channel.numberOfChildren(); i++) {
                if (channel.child(i).label().equals("item")) {
                    processItem(channel.child(i), fileOut);
                }
            }
            // Print closing tags to html output file
            outputFooter(fileOut);
        }
        // Close I/O stream and file output stream
        in.close();
        out.close();
        fileOut.close();
    }
}
